### ISSUE TITLE
Gurobi implementation of QCQP

### ISSUE THREAD

**Issue by caomuqing** [mit-acl/mader#4]
Hi,

Firstly, thanks for this wonderful package. Upon looking into the codes, I realize that the Gurobi version does not implement the original QCQP problem introduced in the paper, but instead it uses the initial guesses of the plane parameters as constants. I would like to ask, is this purely for efficiency reasons, or it is because Gurobi is not capable of solving this type of problem? From Gurobi documentation it seems capable of solving QCQP, but it requires the problem to be convex.
Thank you!

Best Regards,
Mq

**Comment by jtorde** [comment]
Hi @caomuqing,

Thanks for reporting this issue. Yes, as you said, the Gurobi implementation fixes the planes during the optimization. In the NLOPT implementation this is not the case though. 
When coding the Gurobi implementation, we used `Gurobi 8.1`, which as you noted it is not capable of solving nonconvex problems. Hence, the planes need to be fixed in that case. 

However, Gurobi [recently added](https://www.gurobi.com/resource/non-convex-quadratic-optimization/) a support for nonconvex problems (in `Gurobi 9.0`), so optimizing the planes could be an option.

Hope this helps!

**Comment by caomuqing** [comment]
Hi jtorde,

Thanks for your information! I have tried the nonconvex quadratically constrained optimization of Gurobi, and it appears to be working. I will try to implement this and submit a pull request in the near future.

Best Regards,
Mq
